# Weights & Biases configuration
WANDB_MODE: "online" # Change to "online" for logging and include appropriate ENTITY and PROJECT arguments
ENTITY: ""
PROJECT: ""
RUN_NAME: "MAPPO - Base"

# Environment configuration
ENV_NAME: "Craftax-Coop-Symbolic" # Can be changed to "Craftax-Coop-Symbolic", "Craftax-Coop-Pixels", "Craftax-MA-Symbolic", "Craftax-MA-Pixels"

# Model parameters
ALG_NAME: "mappo-rnn"
GRU_HIDDEN_DIM: 512
FC_DIM_SIZE: 128
ACTIVATION: "tanh"

# Training parameters
TOTAL_TIMESTEPS: 100000000
NUM_ENVS: 128
NUM_STEPS: 64
NUM_MINIBATCHES: 8
UPDATE_EPOCHS: 4
GAE_LAMBDA: 0.8
GAMMA: 0.99
CLIP_EPS: 0.2
SCALE_CLIP_EPS: false
ENT_COEF: 0.01
VF_COEF: 0.5
ANNEAL_LR: true
LR: 0.0002
MAX_GRAD_NORM: 1.0
LR_WARMUP: 0.0
REW_SHAPING_HORIZON: 1000000

# Seed configuration
NUM_SEEDS: 1
SEED: 0

# Output configuration
OUTPUT_DIR: "/n/holylfs06/LABS/krajan_lab/Lab/foraging/Craftax_Coop_trade_test8_01_16_26"
# Rendering configuration
RENDER_DURING_TRAINING: true
RENDER_INTERVAL: 1  # Render every N blocks (not updates!)
UPDATES_PER_BLOCK: 50  # How many updates per training block
RENDER_EGO_PERSPECTIVE: true
RENDER_FULL_MAP: true
MAX_EPISODE_STEPS: 1000
