# Weights & Biases configuration
WANDB_MODE: "online" # Change to "online" for logging and include appropriate ENTITY and PROJECT arguments
ENTITY: ""
PROJECT: ""
RUN_NAME: "PQN - Base"

# Environment configuration
ENV_NAME: "Craftax-Coop-Symbolic" # Can be changed to "Craftax-Coop-Symbolic", "Craftax-Coop-Pixels", "Craftax-MA-Symbolic", "Craftax-MA-Pixels"

# Model parameters
ALG_NAME: "pqn-vdn-rnn"
HIDDEN_SIZE: 1024
NUM_LAYERS: 1
NUM_RNN_LAYERS: 1
ADD_LAST_ACTION: true
NORM_INPUT: true
NORM_TYPE: "layer_norm"

# Training parameters
TOTAL_TIMESTEPS: 1.0e+9
TOTAL_TIMESTEPS_DECAY: 1.0e+9
NUM_ENVS: 512
MEMORY_WINDOW: 0
NUM_STEPS: 128
EPS_START: 1.0
EPS_FINISH: 0.005
EPS_DECAY: 0.1
NUM_MINIBATCHES: 4
NUM_EPOCHS: 4
LR: 0.00005
MAX_GRAD_NORM: 0.5
LR_LINEAR_DECAY: true
REW_SCALE: 1.0
GAMMA: 0.99
LAMBDA: 0.9

# Seed configuration
NUM_SEEDS: 1
SEED: 0
